[package]
name = "kash"
version = "0.1.0"
authors = ["Omid Rad <omidmr@gmail.com>", "James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/omid/kash"
documentation = "https://docs.rs/kash"
readme = "README.md"
categories = ["caching", "data-structures"]
keywords = ["cache", "memoize", "lru", "redis", "disk"]
license = "MIT"
edition = "2021"
rust-version = "1.76"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["proc_macro", "ahash"]
proc_macro = ["dep:kash_proc_macro"]
ahash = ["dep:ahash", "hashbrown/default"]
async = ["dep:futures", "dep:tokio", "dep:async-trait"]
async_tokio_rt_multi_thread = ["async", "tokio/rt-multi-thread"]
redis_store = ["dep:redis", "dep:r2d2", "dep:serde", "dep:serde_json"]
redis_connection_manager = ["redis_store", "redis/connection-manager"]
redis_async_std = [
    "redis_store",
    "async",
    "redis/aio",
    "redis/async-std-comp",
    "redis/tls",
    "redis/async-std-tls-comp",
]
redis_tokio = [
    "redis_store",
    "async",
    "redis/aio",
    "redis/tokio-comp",
    "redis/tls",
    "redis/tokio-native-tls-comp",
]
redis_ahash = ["redis_store", "redis/ahash"]
disk_store = ["dep:sled", "dep:serde", "dep:rmp-serde", "dep:directories"]
wasm = []

[dependencies.kash_proc_macro]
version = "0.1"
path = "kash_proc_macro"
optional = true

[dependencies.hashbrown]
version = "0.14"
default-features = false
features = ["raw", "inline-more"]

[dependencies.once_cell]
version = "1"

[dependencies.thiserror]
version = "1"

[dependencies.ahash]
version = "0.8"
default-features = false
optional = true

[dependencies.futures]
version = "0.3"
default-features = false
optional = true

[dependencies.async-trait]
version = "0.1"
optional = true

[dependencies.redis]
version = "0.26"
features = ["r2d2"]
optional = true

[dependencies.sled]
version = "0.34"
optional = true

[dependencies.rmp-serde]
version = "1.1"
optional = true

[dependencies.directories]
version = "5.0"
optional = true

[dependencies.r2d2]
version = "0.8"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.tokio]
version = "1"
features = ["macros", "time", "sync", "parking_lot"]
optional = true

[dependencies.web-time]
version = "^1.1.0"

[dev-dependencies]
copy_dir = "0.1.3"
googletest = "0.12.0"
tempfile = "3.10.1"

[dev-dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dev-dependencies.smartstring]
version = "1"

[dev-dependencies.serial_test]
version = "3"

[workspace]
members = ["kash_proc_macro", "examples/wasm"]

[[example]]
name = "redis"
required-features = ["redis_store", "proc_macro"]

[[example]]
name = "redis-async"
required-features = ["async", "proc_macro"]

[[example]]
name = "tokio"
required-features = ["async", "proc_macro"]

[[example]]
name = "async_std"
required-features = ["async", "proc_macro"]

[[example]]
name = "expiring_sized_cache"
required-features = ["async_tokio_rt_multi_thread"]

[[example]]
name = "disk"
required-features = ["disk_store"]
