[package]
name = "kash"
version = "0.1.0"
authors = ["Omid Rad <omidmr@gmail.com>", "James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/omid/kash"
documentation = "https://docs.rs/kash"
readme = "README.md"
categories = ["caching", "data-structures"]
keywords = ["cache", "memoize", "lru", "redis", "disk"]
license = "MIT"
edition = "2021"
rust-version = "1.76"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["proc_macro"]
proc_macro = ["dep:kash_proc_macro"]
async = ["moka/future"]
redis_store = ["dep:redis", "dep:r2d2", "dep:serde", "dep:serde_json"]
redis_connection_manager = ["redis_store", "redis/connection-manager"]
redis_async_std = [
    "redis_store",
    "async",
    "redis/aio",
    "redis/async-std-comp",
    "redis/tls",
    "redis/async-std-tls-comp",
]
redis_tokio = [
    "redis_store",
    "async",
    "redis/aio",
    "redis/tokio-comp",
    "redis/tls",
    "redis/tokio-native-tls-comp",
]
redis_ahash = ["redis_store", "redis/ahash"]
disk_store = ["dep:sled", "dep:serde", "dep:rmp-serde", "dep:directories"]

[dependencies]
async-trait = { version = "0.1" }
directories = { version = "5.0", optional = true }
futures = { version = "0.3", default-features = false }
hashbrown ={ version = "0.14", default-features = false, features = ["raw", "inline-more"] }
kash_proc_macro = { path = "kash_proc_macro", optional = true, version = "0.1" }
moka = { version = "0.12", features = ["sync"]}
once_cell = "1"
r2d2 = { version = "0.8", optional = true }
redis = { version = "0.26", features = ["r2d2"], optional = true }
rmp-serde = { version = "1.1", optional = true }
serde = { version = "1.0", features = [ "derive"], optional = true }
serde_json = { version = "1.0", optional = true }
sled = { version = "0.34", optional = true }
thiserror = "1"
tokio = { version = "1.0", features = ["macros", "time", "sync", "parking_lot"] }
web-time = { version = "^1.1.0" }

[dev-dependencies]
async-std = { version = "1.10", features = ["attributes"] }
copy_dir = "0.1.3"
googletest = "0.12.0"
serial_test = "3"
smartstring = "1"
tempfile = "3.10.1"

[workspace]
members = ["kash_proc_macro"]

[[example]]
name = "redis"
required-features = ["redis_store", "proc_macro"]

[[example]]
name = "redis-async"
required-features = ["async", "proc_macro"]

[[example]]
name = "tokio"
required-features = ["async", "proc_macro"]

[[example]]
name = "async_std"
required-features = ["async", "proc_macro"]

[[example]]
name = "expiring_sized_cache"
required-features = ["async_tokio_rt_multi_thread"]

[[example]]
name = "disk"
required-features = ["disk_store"]
