[package]
name = "wasm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.kash]
path = "../.."
default-features = false
features = ["proc_macro", "wasm", "async"]

[dependencies.chrono]
version = "0.4"
features = ["wasmbind"]

[dependencies.reqwasm]
version = "0.5"

[dependencies.wasm-bindgen-futures]
version = "0.4"

[dependencies.yew]
version = "0.19.3"
