name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - run: cargo install cargo-readme
    - name: 'Running `make ci`'
      run: make check
      
  test:
    needs: check
    strategy:
      matrix:
        target:
        - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
#        - { name: macOS, os: macos-latest, triple: x86_64-apple-darwin }
        - { name: Windows, os: windows-2022, triple: x86_64-pc-windows-msvc }
        version:
        - 1.76.0 # MSRV
        - stable
        - nightly
    runs-on: ${{ matrix.target.os }}
    name:
      ${{ matrix.target.name }} / ${{ matrix.version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install ${{ matrix.version }}
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.version }}-${{ matrix.target.triple }}
        override: true
    - name: Run tests
      run: make tests examples
